"""Hindsight 0.10.1 access. Everything outside this package goes through `HindsightGateway`."""

from atlas.hindsight.errors import (
    HindsightError,
    HindsightHTTPError,
    HindsightNotFound,
    HindsightProtocolError,
    HindsightRuleViolation,
    HindsightUnavailable,
    OperationTimeout,
)
from atlas.hindsight.gateway import HindsightGateway
from atlas.hindsight.models import (
    BankConfig,
    Budget,
    CitedMemory,
    CitedMentalModel,
    KnowledgeNode,
    LlmRequestStats,
    Memory,
    MentalModel,
    MentalModelDefinition,
    MentalModelRevision,
    MentalModelSubmitted,
    MentalModelTrigger,
    ObservationPage,
    Operation,
    OperationStatus,
    OperationSubmitted,
    RecallResult,
    ReflectAnswer,
    RetainedDocument,
    RetainItem,
    RetainSubmitted,
    TagMatch,
    TagScope,
    TemplateApplication,
    TemplateImportResult,
)

__all__ = [
    "BankConfig",
    "Budget",
    "CitedMemory",
    "CitedMentalModel",
    "HindsightError",
    "HindsightGateway",
    "HindsightHTTPError",
    "HindsightNotFound",
    "HindsightProtocolError",
    "HindsightRuleViolation",
    "HindsightUnavailable",
    "KnowledgeNode",
    "LlmRequestStats",
    "Memory",
    "MentalModel",
    "MentalModelDefinition",
    "MentalModelRevision",
    "MentalModelSubmitted",
    "MentalModelTrigger",
    "ObservationPage",
    "Operation",
    "OperationStatus",
    "OperationSubmitted",
    "OperationTimeout",
    "RecallResult",
    "ReflectAnswer",
    "RetainItem",
    "RetainSubmitted",
    "RetainedDocument",
    "TagMatch",
    "TagScope",
    "TemplateApplication",
    "TemplateImportResult",
]
