/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Companies */
        get: operations["companies_api_v1_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company */
        get: operations["company_api_v1_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Sources */
        get: operations["company_sources_api_v1_companies__company_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_api_v1_sources__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{document_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Versions */
        get: operations["source_versions_api_v1_sources__document_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Version */
        get: operations["source_version_api_v1_source_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-versions/{version_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Version Content */
        get: operations["source_version_content_api_v1_source_versions__version_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Company */
        Company: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Legal Name */
            legal_name: string;
            /** Display Name */
            display_name: string;
            /** Cik */
            cik: string | null;
            /** Lei */
            lei: string | null;
            /** Country */
            country: string;
            /** Website */
            website: string | null;
            /** Parent Company Id */
            parent_company_id: string | null;
            /** Review State */
            review_state: string;
            /** Securities */
            securities: components["schemas"]["Security"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ContentLinks */
        ContentLinks: {
            /** Raw */
            raw: string;
            /** Parsed */
            parsed: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * FetchObservation
         * @description One fetch of the document that produced or matched this version.
         */
        FetchObservation: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Outcome */
            outcome: string;
            /** Url */
            url: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Raw Sha256 */
            raw_sha256: string | null;
            /** Comparison Sha256 */
            comparison_sha256: string | null;
            /** Etag */
            etag: string | null;
            /** Last Modified */
            last_modified: string | null;
            /** Attempts */
            attempts: number;
            /** Job Id */
            job_id: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Job */
        Job: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Payload */
            payload: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Lease Owner */
            lease_owner: string | null;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Failures */
            failures: components["schemas"]["JobFailure"][];
            /** Artifacts */
            artifacts: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** JobFailure */
        JobFailure: {
            /** Attempt */
            attempt: number;
            /** Error */
            error: string;
            /** Worker */
            worker: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        JsonValue: unknown;
        /** Page[Company] */
        Page_Company_: {
            /** Items */
            items: components["schemas"]["Company"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SourceDocument] */
        Page_SourceDocument_: {
            /** Items */
            items: components["schemas"]["SourceDocument"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SourceVersionSummary] */
        Page_SourceVersionSummary_: {
            /** Items */
            items: components["schemas"]["SourceVersionSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Security */
        Security: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticker */
            ticker: string;
            /** Exchange Mic */
            exchange_mic: string;
            /** Instrument Type */
            instrument_type: string;
            /** Currency */
            currency: string;
            /** Isin */
            isin: string | null;
            /** Figi */
            figi: string | null;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
        };
        /** SourceDocument */
        SourceDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Id */
            company_id: string | null;
            /** Provider */
            provider: string;
            /** Canonical Url */
            canonical_url: string;
            /** Origin Url */
            origin_url: string;
            /** Accession */
            accession: string | null;
            /** Form Type */
            form_type: string | null;
            /** Document Type */
            document_type: string | null;
            /** Source Type */
            source_type: string;
            /** Title */
            title: string;
            /** Publisher */
            publisher: string;
            /** Source Tier */
            source_tier: string;
            /** License Class */
            license_class: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Version Count */
            version_count: number;
            /** Latest Version Id */
            latest_version_id: string | null;
        };
        /**
         * SourceVersionDetail
         * @description A Source Version's full provenance.
         */
        SourceVersionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /** Version Number */
            version_number: number;
            /** Raw Sha256 */
            raw_sha256: string;
            /** Content Sha256 */
            content_sha256: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Parse Status */
            parse_status: string;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Available At Basis */
            available_at_basis: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Supersedes Version Id */
            supersedes_version_id: string | null;
            /** Superseded By Version Id */
            superseded_by_version_id: string | null;
            source_document: components["schemas"]["SourceDocument"];
            /** Comparison Sha256 */
            comparison_sha256: string;
            /** Comparison Rule */
            comparison_rule: string;
            /** Object Uri */
            object_uri: string;
            /** Parsed Object Uri */
            parsed_object_uri: string | null;
            /** Byte Size */
            byte_size: number;
            /** Media Type */
            media_type: string;
            /** Parse Error */
            parse_error: string | null;
            /** Event At */
            event_at: string | null;
            /** Published At */
            published_at: string | null;
            /** Fetch Status */
            fetch_status: string;
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            content: components["schemas"]["ContentLinks"];
            /** Fetches */
            fetches: components["schemas"]["FetchObservation"][];
        };
        /** SourceVersionSummary */
        SourceVersionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /** Version Number */
            version_number: number;
            /** Raw Sha256 */
            raw_sha256: string;
            /** Content Sha256 */
            content_sha256: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Parse Status */
            parse_status: string;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Available At Basis */
            available_at_basis: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Supersedes Version Id */
            supersedes_version_id: string | null;
            /** Superseded By Version Id */
            superseded_by_version_id: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    companies_api_v1_companies_get: {
        parameters: {
            query?: {
                /** @description page size */
                limit?: number;
                /** @description items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Company_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_api_v1_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_sources_api_v1_companies__company_id__sources_get: {
        parameters: {
            query?: {
                /** @description page size */
                limit?: number;
                /** @description items to skip */
                offset?: number;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SourceDocument_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_api_v1_sources__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_versions_api_v1_sources__document_id__versions_get: {
        parameters: {
            query?: {
                /** @description page size */
                limit?: number;
                /** @description items to skip */
                offset?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SourceVersionSummary_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_version_api_v1_source_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceVersionDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_version_content_api_v1_source_versions__version_id__content_get: {
        parameters: {
            query: {
                /** @description raw bytes or the parsed text */
                kind: "raw" | "parsed";
            };
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived bytes (raw) or UTF-8 text (parsed) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
