/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Queue */
        get: operations["get_queue_api_v1_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Companies */
        get: operations["companies_api_v1_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company */
        get: operations["company_api_v1_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Sources */
        get: operations["company_sources_api_v1_companies__company_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_api_v1_sources__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{document_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Versions */
        get: operations["source_versions_api_v1_sources__document_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Version */
        get: operations["source_version_api_v1_source_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-versions/{version_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Version Content */
        get: operations["source_version_content_api_v1_source_versions__version_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence-families/{family_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence Family */
        get: operations["evidence_family_api_v1_evidence_families__family_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assertions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assertions */
        get: operations["assertions_api_v1_assertions_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_assertions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assertions/{assertion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assertion */
        get: operations["assertion_api_v1_assertions__assertion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assertions/{assertion_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_v1_assertions__assertion_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-versions/{version_id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Version Memory Documents */
        get: operations["source_version_memory_documents_api_v1_source_versions__version_id__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recall */
        post: operations["recall_api_v1_memory_recall_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/reflect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reflect */
        post: operations["reflect_api_v1_memory_reflect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/reflect/{answer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reflect Answer */
        get: operations["reflect_answer_api_v1_memory_reflect__answer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mental-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mental Models */
        get: operations["list_mental_models_api_v1_mental_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mental-models/{mental_model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mental Model */
        get: operations["get_mental_model_api_v1_mental_models__mental_model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/role-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Role Calls */
        get: operations["role_calls_api_v1_runs__run_id__role_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Claims */
        get: operations["claims_api_v1_claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Claim */
        get: operations["claim_api_v1_claims__claim_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claim-extractions/{extraction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Extraction */
        get: operations["extraction_api_v1_claim_extractions__extraction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AnswerStatus: "pending" | "running" | "completed" | "failed";
        /**
         * AppliedScope
         * @description The scope as sent to Hindsight: the tags and their strict match mode.
         */
        AppliedScope: {
            /** Company Ids */
            company_ids: string[];
            /** Theme Ids */
            theme_ids: string[];
            /** Tags */
            tags: string[];
            tags_match: components["schemas"]["TagMatch"];
        };
        /** Assertion */
        Assertion: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Subject Company Id
             * Format: uuid
             */
            subject_company_id: string;
            /** Predicate */
            predicate: string;
            /** Object Company Id */
            object_company_id: string | null;
            value_json: components["schemas"]["JsonValue"];
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /** Quote */
            quote: string;
            /** Span Start */
            span_start: number;
            /** Span End */
            span_end: number;
            /** Page Or Anchor */
            page_or_anchor: string | null;
            /** Event Start */
            event_start: string | null;
            /** Event End */
            event_end: string | null;
            /**
             * Epistemic Type
             * @enum {string}
             */
            epistemic_type: "direct_source_statement" | "company_claim" | "third_party_report" | "agent_inference" | "quantitative_derived";
            /**
             * Review State
             * @enum {string}
             */
            review_state: "unreviewed" | "corroborated" | "disputed" | "rejected" | "superseded";
            /** Independence Family Id */
            independence_family_id: string | null;
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at: string;
            /** Extractor Version */
            extractor_version: string;
            /** Created By */
            created_by: string;
            /** Reviewer Id */
            reviewer_id: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Superseded By */
            superseded_by: string | null;
        };
        /**
         * AssertionCreate
         * @description A researcher's new Assertion. Review fields are not accepted: it starts unreviewed.
         */
        AssertionCreate: {
            /**
             * Subject Company Id
             * Format: uuid
             */
            subject_company_id: string;
            /** Predicate */
            predicate: string;
            /** Object Company Id */
            object_company_id?: string | null;
            value_json?: components["schemas"]["JsonValue"];
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /**
             * Quote
             * @description exactly the parsed text at the offsets
             */
            quote: string;
            /**
             * Span Start
             * @description first character of the quote in the parse
             */
            span_start: number;
            /**
             * Span End
             * @description one past the quote's last character
             */
            span_end: number;
            /** Page Or Anchor */
            page_or_anchor?: string | null;
            /** Event Start */
            event_start?: string | null;
            /** Event End */
            event_end?: string | null;
            /**
             * Epistemic Type
             * @enum {string}
             */
            epistemic_type: "direct_source_statement" | "company_claim" | "third_party_report" | "agent_inference" | "quantitative_derived";
        };
        /**
         * AssertionRecorded
         * @description A mutation's result: the Assertion as it now is, and the audit event recording it.
         */
        AssertionRecorded: {
            assertion: components["schemas"]["Assertion"];
            /** Audit Event Id */
            audit_event_id: number;
        };
        /** AssertionReview */
        AssertionReview: {
            /**
             * Review State
             * @enum {string}
             */
            review_state: "unreviewed" | "corroborated" | "disputed" | "rejected" | "superseded";
            /**
             * Superseded By
             * @description the successor; required exactly when superseding
             */
            superseded_by?: string | null;
        };
        /** BackfillWindowStatus */
        BackfillWindowStatus: {
            /** Window */
            window: string | null;
            /** Timezone */
            timezone: string | null;
            /** Open */
            open: boolean;
            /** Next Open At */
            next_open_at: string | null;
        };
        /** @enum {string} */
        Budget: "low" | "mid" | "high";
        /** Citation */
        Citation: {
            kind: components["schemas"]["CitationKind"];
            state: components["schemas"]["CitationState"];
            reason: components["schemas"]["UnresolvedReason"] | null;
            /** Detail */
            detail: string | null;
            /** Memory Id */
            memory_id: string | null;
            /** Memory Type */
            memory_type: string | null;
            /** Text */
            text: string;
            /** Sources */
            sources: components["schemas"]["CitationSource"][];
            /** Missing Memory Ids */
            missing_memory_ids: string[];
            quote: components["schemas"]["QuoteSpan"] | null;
        };
        /** @enum {string} */
        CitationKind: "memory" | "chunk" | "quote";
        /**
         * CitationSource
         * @description A world fact resolved to the Source Version section it was extracted from.
         */
        CitationSource: {
            /** Memory Id */
            memory_id: string;
            /** Document Id */
            document_id: string;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /** Company Id */
            company_id: string | null;
            /** Form Type */
            form_type: string | null;
            /** Section Anchor */
            section_anchor: string;
            /** Section Heading */
            section_heading: string | null;
            /** Section Char Start */
            section_char_start: number;
            /** Section Char End */
            section_char_end: number;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Available At Basis */
            available_at_basis: string;
        };
        /** @enum {string} */
        CitationState: "resolved" | "unverified" | "broken";
        /**
         * Claim
         * @description One proposed Claim and its outcome. `proposed` is the Claim exactly as the model
         *     answered; the other fields are what Atlas resolved from it (null when it couldn't).
         */
        Claim: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Extraction Id
             * Format: uuid
             */
            extraction_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Role Call Id
             * Format: uuid
             */
            role_call_id: string;
            /** Passage Id */
            passage_id: string;
            /** Source Version Id */
            source_version_id: string | null;
            /** Subject Company Id */
            subject_company_id: string | null;
            /** Predicate */
            predicate: string;
            /** Object Company Id */
            object_company_id: string | null;
            /** Object Text */
            object_text: string | null;
            /** Product */
            product: string | null;
            /** Layer */
            layer: string;
            /** Quote */
            quote: string;
            /** Span Start */
            span_start: number | null;
            /** Span End */
            span_end: number | null;
            /** Epistemic Type */
            epistemic_type: string;
            /** Directional Cue */
            directional_cue: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "accepted" | "rejected";
            /** Reason Code */
            reason_code: string | null;
            /** Reason */
            reason: string | null;
            /** Assertion Id */
            assertion_id: string | null;
            /** Proposed */
            proposed: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ClaimExtraction */
        ClaimExtraction: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Source Version Ids */
            source_version_ids: string[];
            /** Question */
            question: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "budget_exhausted";
            /** Passages */
            passages: components["schemas"]["Passage"][];
            /** Passages Dropped */
            passages_dropped: number;
            /** Passages Per Call */
            passages_per_call: number;
            /** Skipped */
            skipped: components["schemas"]["SkippedVersion"][];
            /** Batches Total */
            batches_total: number;
            /** Batches Done */
            batches_done: number;
            /** Batches Quarantined */
            batches_quarantined: number;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** Company */
        Company: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Legal Name */
            legal_name: string;
            /** Display Name */
            display_name: string;
            /** Cik */
            cik: string | null;
            /** Lei */
            lei: string | null;
            /** Country */
            country: string;
            /** Website */
            website: string | null;
            layer: components["schemas"]["Layer"] | null;
            source_path: components["schemas"]["SourcePath"] | null;
            /** Sec Forms */
            sec_forms: string[] | null;
            /** Parent Company Id */
            parent_company_id: string | null;
            /** Review State */
            review_state: string;
            /** Securities */
            securities: components["schemas"]["Security"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ContentLinks */
        ContentLinks: {
            /** Raw */
            raw: string;
            /** Parsed */
            parsed: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * Evidence
         * @description A Source Version section that resolved citations lead to (Evidence, not Memory).
         */
        Evidence: {
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /** Company Id */
            company_id: string | null;
            /** Form Type */
            form_type: string | null;
            /** Section Anchor */
            section_anchor: string;
            /** Section Heading */
            section_heading: string | null;
            /** Section Char Start */
            section_char_start: number;
            /** Section Char End */
            section_char_end: number;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Available At Basis */
            available_at_basis: string;
            /** Memory Ids */
            memory_ids: string[];
            /** Quotes */
            quotes: components["schemas"]["QuoteSpan"][];
        };
        /**
         * EvidenceFamily
         * @description Source Versions that are copies of one announcement: one witness.
         */
        EvidenceFamily: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Simhash Rule */
            simhash_rule: string;
            /** Max Hamming Distance */
            max_hamming_distance: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Member Count */
            member_count: number;
            /** Members */
            members: components["schemas"]["EvidenceFamilyMember"][];
        };
        /** EvidenceFamilyMember */
        EvidenceFamilyMember: {
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /** Canonical Url */
            canonical_url: string;
            /** Publisher */
            publisher: string;
            /**
             * Match
             * @enum {string}
             */
            match: "founder" | "content_hash" | "simhash";
            /** Matched Source Version Id */
            matched_source_version_id: string | null;
            /** Hamming Distance */
            hamming_distance: number | null;
            /** Simhash */
            simhash: string;
            /**
             * Assigned At
             * Format: date-time
             */
            assigned_at: string;
        };
        /**
         * EvidenceFamilyMembership
         * @description How a Source Version joined its Evidence Family (atlas.ledger.families).
         */
        EvidenceFamilyMembership: {
            /**
             * Evidence Family Id
             * Format: uuid
             */
            evidence_family_id: string;
            /**
             * Match
             * @enum {string}
             */
            match: "founder" | "content_hash" | "simhash";
            /** Matched Source Version Id */
            matched_source_version_id: string | null;
            /** Hamming Distance */
            hamming_distance: number | null;
            /** Simhash */
            simhash: string;
            /** Simhash Rule */
            simhash_rule: string;
            /** Max Hamming Distance */
            max_hamming_distance: number;
            /** Member Count */
            member_count: number;
            /**
             * Assigned At
             * Format: date-time
             */
            assigned_at: string;
        };
        /**
         * FetchObservation
         * @description One fetch of the document that produced or matched this version.
         */
        FetchObservation: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Outcome */
            outcome: string;
            /** Url */
            url: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Raw Sha256 */
            raw_sha256: string | null;
            /** Comparison Sha256 */
            comparison_sha256: string | null;
            /** Etag */
            etag: string | null;
            /** Last Modified */
            last_modified: string | null;
            /** Attempts */
            attempts: number;
            /** Job Id */
            job_id: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Job */
        Job: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Job Class
             * @enum {string}
             */
            job_class: "interactive" | "backfill";
            /** Payload */
            payload: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Lease Owner */
            lease_owner: string | null;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Failures */
            failures: components["schemas"]["JobFailure"][];
            /** Artifacts */
            artifacts: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** JobFailure */
        JobFailure: {
            /** Attempt */
            attempt: number;
            /** Error */
            error: string;
            /** Worker */
            worker: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Classification */
            classification?: ("quota" | "unavailable" | "error" | "lease_expired") | null;
        };
        JsonValue: unknown;
        /** @enum {string} */
        Layer: "substrate" | "epi" | "chip-laser" | "dsp" | "module" | "contract-manufacturing" | "system";
        /**
         * LLMAttempt
         * @description One chat completion: the routed model, its usage, its raw content and why it failed
         *     validation (None: it validated).
         */
        LLMAttempt: {
            /** Attempt */
            attempt: number;
            /** Response Model */
            response_model: string;
            /** Model Id */
            model_id: string | null;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Content */
            content: string;
            /** Validation Errors */
            validation_errors: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | null;
            /**
             * Called At
             * Format: date-time
             */
            called_at: string;
        };
        /**
         * MemoryDocument
         * @description One section of the Source Version, as retained (or linked) into the bank.
         */
        MemoryDocument: {
            /** Section Anchor */
            section_anchor: string;
            /** Section Heading */
            section_heading: string | null;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Sectioner Version */
            sectioner_version: string;
            /** Document Id */
            document_id: string | null;
            /**
             * Retain State
             * @enum {string}
             */
            retain_state: "pending" | "completed" | "failed" | "zero_fact" | "linked";
            /** Fact Count */
            fact_count: number | null;
            /** Memory Ids */
            memory_ids: string[] | null;
            /** Reprocess Count */
            reprocess_count: number;
            /** Template Version */
            template_version: string;
            /** Operation Id */
            operation_id: string | null;
            /** Linked To Source Version Id */
            linked_to_source_version_id: string | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MemoryOperation
         * @description A Hindsight operation that retained (or reprocessed) some of the version's sections.
         */
        MemoryOperation: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Error Message */
            error_message: string | null;
            /** Error Class */
            error_class: ("quota" | "unavailable" | "permanent") | null;
            /** Retry Count */
            retry_count: number;
            /** Document Ids */
            document_ids: string[];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Last Polled At */
            last_polled_at: string | null;
            /** Completed At */
            completed_at: string | null;
        };
        /** MentalModelList */
        MentalModelList: {
            /** Bank Id */
            bank_id: string;
            /** Template Version */
            template_version: string;
            /** Mental Models */
            mental_models: components["schemas"]["MentalModelView"][];
        };
        /**
         * MentalModelRefresh
         * @description One decision of a `refresh_mental_model` job.
         */
        MentalModelRefresh: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Scheduled For */
            scheduled_for: string | null;
            /** Template Version */
            template_version: string | null;
            /** Min Refresh Interval Seconds */
            min_refresh_interval_seconds: number;
            /**
             * Status
             * @enum {string}
             */
            status: "skipped" | "submitted" | "completed" | "failed";
            /** Skip Reason */
            skip_reason: ("min_interval" | "not_stale") | null;
            /** Operation Id */
            operation_id: string | null;
            /** Run Id */
            run_id: string | null;
            /** Operation Status */
            operation_status: string | null;
            /** Error */
            error: string | null;
            /** Error Class */
            error_class: ("quota" | "unavailable" | "permanent") | null;
            /** Previous Refreshed At */
            previous_refreshed_at: string | null;
            /** Refreshed At */
            refreshed_at: string | null;
            /** Content Sha256 */
            content_sha256: string | null;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * MentalModelRevision
         * @description The content a refresh replaced at `changed_at`, with its citations resolved.
         */
        MentalModelRevision: {
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
            /** Previous Content */
            previous_content: string | null;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** MentalModelView */
        MentalModelView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Source Query */
            source_query: string;
            trigger: components["schemas"]["RefreshTrigger"];
            /** Bank Id */
            bank_id: string;
            /** In Bank */
            in_bank: boolean;
            /** Content */
            content: string | null;
            /** Last Refreshed At */
            last_refreshed_at: string | null;
            /** Is Stale */
            is_stale: boolean | null;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Evidence Missing */
            evidence_missing: boolean | null;
            /** Quote Rule */
            quote_rule: string;
            /** History */
            history: components["schemas"]["MentalModelRevision"][];
            /** Refreshes */
            refreshes: components["schemas"]["MentalModelRefresh"][];
        };
        /**
         * PageAnchor
         * @description One PDF page's place in the parsed text: `text[start:end]`, in code points.
         */
        PageAnchor: {
            /** Page */
            page: number;
            /** Label */
            label: string;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** Page[Assertion] */
        Page_Assertion_: {
            /** Items */
            items: components["schemas"]["Assertion"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Claim] */
        Page_Claim_: {
            /** Items */
            items: components["schemas"]["Claim"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Company] */
        Page_Company_: {
            /** Items */
            items: components["schemas"]["Company"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SourceDocument] */
        Page_SourceDocument_: {
            /** Items */
            items: components["schemas"]["SourceDocument"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SourceVersionSummary] */
        Page_SourceVersionSummary_: {
            /** Items */
            items: components["schemas"]["SourceVersionSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * Passage
         * @description A stretch of one Source Version's parsed text sent to the Investigator.
         */
        Passage: {
            /** Id */
            id: string;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /** Section Anchor */
            section_anchor: string;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Selected By */
            selected_by: string[];
        };
        /** PendingKind */
        PendingKind: {
            /** Kind */
            kind: string;
            /** Queued */
            queued: number;
            /** Running */
            running: number;
            /** Backfill Queued */
            backfill_queued: number;
            /** Paused */
            paused: boolean;
        };
        /**
         * QueuePause
         * @description The queue-level pause: which kinds are held back, why, and until when.
         */
        QueuePause: {
            /** Paused */
            paused: boolean;
            /** Level */
            level: number;
            /** Error Class */
            error_class: ("quota" | "unavailable") | null;
            /** Reason */
            reason: string | null;
            /** Kinds */
            kinds: string[];
            /** Backoff Seconds */
            backoff_seconds: number | null;
            /** Paused At */
            paused_at: string | null;
            /** Resume After */
            resume_after: string | null;
            /** Since */
            since: string | null;
            /** Job Id */
            job_id: string | null;
            /** Cleared At */
            cleared_at: string | null;
            /** Pauses Total */
            pauses_total: number;
        };
        /** QueueStatus */
        QueueStatus: {
            /**
             * Now
             * Format: date-time
             */
            now: string;
            pause: components["schemas"]["QueuePause"];
            backfill_window: components["schemas"]["BackfillWindowStatus"];
            /** Pending */
            pending: components["schemas"]["PendingKind"][];
        };
        /**
         * QuoteSpan
         * @description A quote matched in the archived parsed text: code-point offsets, like an Assertion's.
         */
        QuoteSpan: {
            /** Quoted */
            quoted: string;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Archived Text */
            archived_text: string;
        };
        /**
         * QuotedText
         * @description Retrieved text passed to a role: always quoted, always low-trust data (spec §7.5).
         */
        QuotedText: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Text */
            text: string;
            /**
             * Trust
             * @default low
             * @constant
             */
            trust: "low";
        };
        /** RecallRequest */
        RecallRequest: {
            /** Query */
            query: string;
            scope: components["schemas"]["ResearchScope"];
            /** @default mid */
            budget: components["schemas"]["Budget"];
        };
        /** RecallResponse */
        RecallResponse: {
            /** Query */
            query: string;
            scope: components["schemas"]["AppliedScope"];
            /** Memories */
            memories: components["schemas"]["RecalledMemory"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** RecalledMemory */
        RecalledMemory: {
            /** Memory Id */
            memory_id: string;
            /** Type */
            type: string;
            /** Text */
            text: string;
            /** Context */
            context: string | null;
            /** Tags */
            tags: string[];
            /** Occurred Start */
            occurred_start: string | null;
            /** Occurred End */
            occurred_end: string | null;
            /** Mentioned At */
            mentioned_at: string | null;
            provenance: components["schemas"]["Citation"];
        };
        /** ReflectAccepted */
        ReflectAccepted: {
            research_answer: components["schemas"]["ResearchAnswer"];
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Audit Event Id */
            audit_event_id: number;
        };
        /** ReflectRequest */
        ReflectRequest: {
            /** Question */
            question: string;
            scope: components["schemas"]["ResearchScope"];
            /**
             * Response Schema
             * @description a JSON Schema object for structured output; union types are refused
             */
            response_schema?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
        };
        /**
         * RefreshTrigger
         * @description When the model is refreshed, as the bank template defines it.
         */
        RefreshTrigger: {
            /** Refresh After Consolidation */
            refresh_after_consolidation: boolean;
            /** Refresh Cron */
            refresh_cron: string;
            /** Min Refresh Interval Seconds */
            min_refresh_interval_seconds: number;
        };
        /** ResearchAnswer */
        ResearchAnswer: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Bank Id */
            bank_id: string;
            status: components["schemas"]["AnswerStatus"];
            /** Question */
            question: string;
            scope: components["schemas"]["AppliedScope"];
            /** Response Schema */
            response_schema: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Answer */
            answer: string | null;
            /** Structured Output */
            structured_output: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Structured Output Error */
            structured_output_error: string | null;
            /** Raw Citations */
            raw_citations: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | null;
            /** Citations */
            citations: components["schemas"]["Citation"][] | null;
            /** Counts */
            counts: {
                [key: string]: number;
            } | null;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][] | null;
            /** Evidence Missing */
            evidence_missing: boolean | null;
            /** Quote Rule */
            quote_rule: string | null;
            /** Run Id */
            run_id: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Job Status */
            job_status: ("queued" | "running" | "succeeded" | "failed") | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Answered At */
            answered_at: string | null;
        };
        /** ResearchScope */
        ResearchScope: {
            /** Company Ids */
            company_ids?: string[];
            /**
             * Theme Ids
             * @description theme slugs, e.g. photonics
             */
            theme_ids?: string[];
        };
        /**
         * RoleCallRecord
         * @description One call of a role. A quarantined call's outputs are visible in its attempts only;
         *     `output` is set only for an accepted call.
         */
        RoleCallRecord: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Prompt Name */
            prompt_name: string;
            /** Prompt Version */
            prompt_version: number;
            /** Prompt Sha256 */
            prompt_sha256: string;
            /** Model */
            model: string;
            /** Request */
            request: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Retrieved */
            retrieved: components["schemas"]["QuotedText"][];
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "accepted" | "quarantined" | "failed" | "budget_exhausted";
            /** Output */
            output: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Error */
            error: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Attempts */
            attempts: components["schemas"]["LLMAttempt"][];
        };
        /** RunRoleCalls */
        RunRoleCalls: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Role Calls */
            role_calls: components["schemas"]["RoleCallRecord"][];
        };
        /** Security */
        Security: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticker */
            ticker: string;
            /** Exchange Mic */
            exchange_mic: string;
            /** Instrument Type */
            instrument_type: string;
            /** Currency */
            currency: string;
            /** Isin */
            isin: string | null;
            /** Figi */
            figi: string | null;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
        };
        /** SkippedVersion */
        SkippedVersion: {
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /** Reason */
            reason: string;
        };
        /** SourceDocument */
        SourceDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Id */
            company_id: string | null;
            /** Provider */
            provider: string;
            /** Canonical Url */
            canonical_url: string;
            /** Origin Url */
            origin_url: string;
            /** Accession */
            accession: string | null;
            /** Form Type */
            form_type: string | null;
            /** Document Type */
            document_type: string | null;
            /** Source Type */
            source_type: string;
            /** Title */
            title: string;
            /** Publisher */
            publisher: string;
            /** Source Tier */
            source_tier: string;
            /** License Class */
            license_class: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Version Count */
            version_count: number;
            /** Latest Version Id */
            latest_version_id: string | null;
        };
        /** @enum {string} */
        SourcePath: "sec" | "exchange:hkex" | "exchange:lse-rns" | "exchange:euronext";
        /**
         * SourceVersionDetail
         * @description A Source Version's full provenance.
         */
        SourceVersionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /** Version Number */
            version_number: number;
            /** Raw Sha256 */
            raw_sha256: string;
            /** Content Sha256 */
            content_sha256: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Parse Status */
            parse_status: string;
            /** Language */
            language: string | null;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Available At Basis */
            available_at_basis: string;
            /**
             * Recorded Available At
             * Format: date-time
             */
            recorded_available_at: string;
            /** Recorded Available At Basis */
            recorded_available_at_basis: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Supersedes Version Id */
            supersedes_version_id: string | null;
            /** Superseded By Version Id */
            superseded_by_version_id: string | null;
            /** Evidence Family Id */
            evidence_family_id: string | null;
            source_document: components["schemas"]["SourceDocument"];
            /** Comparison Sha256 */
            comparison_sha256: string;
            /** Comparison Rule */
            comparison_rule: string;
            /** Object Uri */
            object_uri: string;
            /** Parsed Object Uri */
            parsed_object_uri: string | null;
            /** Byte Size */
            byte_size: number;
            /** Media Type */
            media_type: string;
            /** Parse Error */
            parse_error: string | null;
            /** Page Anchors */
            page_anchors: components["schemas"]["PageAnchor"][] | null;
            /** Event At */
            event_at: string | null;
            /** Published At */
            published_at: string | null;
            /** Fetch Status */
            fetch_status: string;
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            content: components["schemas"]["ContentLinks"];
            /** Fetches */
            fetches: components["schemas"]["FetchObservation"][];
            evidence_family: components["schemas"]["EvidenceFamilyMembership"] | null;
        };
        /** SourceVersionMemory */
        SourceVersionMemory: {
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /** Bank Id */
            bank_id: string;
            /** Retained */
            retained: boolean;
            /** Linked To Source Version Id */
            linked_to_source_version_id: string | null;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Fact Count */
            fact_count: number;
            /** Documents */
            documents: components["schemas"]["MemoryDocument"][];
            /** Operations */
            operations: components["schemas"]["MemoryOperation"][];
        };
        /** SourceVersionSummary */
        SourceVersionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Document Id
             * Format: uuid
             */
            source_document_id: string;
            /** Version Number */
            version_number: number;
            /** Raw Sha256 */
            raw_sha256: string;
            /** Content Sha256 */
            content_sha256: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Parse Status */
            parse_status: string;
            /** Language */
            language: string | null;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Available At Basis */
            available_at_basis: string;
            /**
             * Recorded Available At
             * Format: date-time
             */
            recorded_available_at: string;
            /** Recorded Available At Basis */
            recorded_available_at_basis: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Supersedes Version Id */
            supersedes_version_id: string | null;
            /** Superseded By Version Id */
            superseded_by_version_id: string | null;
            /** Evidence Family Id */
            evidence_family_id: string | null;
        };
        /** @enum {string} */
        TagMatch: "any_strict" | "all_strict";
        /** @enum {string} */
        UnresolvedReason: "no_memory_id" | "memory_not_found" | "source_memory_not_found" | "no_source_memories" | "not_an_atlas_document" | "unknown_document" | "metadata_mismatch" | "too_many_hops" | "quote_mismatch";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_queue_api_v1_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueStatus"];
                };
            };
        };
    };
    companies_api_v1_companies_get: {
        parameters: {
            query?: {
                /** @description page size */
                limit?: number;
                /** @description items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Company_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_api_v1_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_sources_api_v1_companies__company_id__sources_get: {
        parameters: {
            query?: {
                /** @description page size */
                limit?: number;
                /** @description items to skip */
                offset?: number;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SourceDocument_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_api_v1_sources__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_versions_api_v1_sources__document_id__versions_get: {
        parameters: {
            query?: {
                /** @description page size */
                limit?: number;
                /** @description items to skip */
                offset?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SourceVersionSummary_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_version_api_v1_source_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceVersionDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_version_content_api_v1_source_versions__version_id__content_get: {
        parameters: {
            query: {
                /** @description raw bytes or the parsed text */
                kind: "raw" | "parsed";
            };
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived bytes (raw) or UTF-8 text (parsed) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_family_api_v1_evidence_families__family_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceFamily"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assertions_api_v1_assertions_get: {
        parameters: {
            query?: {
                /** @description the company as subject or object */
                company_id?: string | null;
                review_state?: ("unreviewed" | "corroborated" | "disputed" | "rejected" | "superseded") | null;
                source_version_id?: string | null;
                /** @description page size */
                limit?: number;
                /** @description items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Assertion_"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_api_v1_assertions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssertionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssertionRecorded"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    assertion_api_v1_assertions__assertion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assertion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assertion"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    review_api_v1_assertions__assertion_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assertion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssertionReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssertionRecorded"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    source_version_memory_documents_api_v1_source_versions__version_id__memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceVersionMemory"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recall_api_v1_memory_recall_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecallResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    reflect_api_v1_memory_reflect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReflectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectAccepted"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    reflect_answer_api_v1_memory_reflect__answer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchAnswer"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_mental_models_api_v1_mental_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentalModelList"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_mental_model_api_v1_mental_models__mental_model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mental_model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentalModelView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    role_calls_api_v1_runs__run_id__role_calls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRoleCalls"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claims_api_v1_claims_get: {
        parameters: {
            query?: {
                extraction_id?: string | null;
                run_id?: string | null;
                source_version_id?: string | null;
                outcome?: ("accepted" | "rejected") | null;
                reason_code?: string | null;
                /** @description page size */
                limit?: number;
                /** @description items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Claim_"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    claim_api_v1_claims__claim_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    extraction_api_v1_claim_extractions__extraction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                extraction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimExtraction"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
